# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-10 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.TextField(blank=True, default='', null=True)),
                ('ubicacion', models.TextField(blank=True, default='', null=True)),
                ('tutor', models.TextField(blank=True, default='', null=True)),
                ('valoracion', models.IntegerField(blank=True, default='0', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='encuentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_encuesta', models.IntegerField(blank=True, default='0', null=True)),
                ('p1', models.TextField(blank=True, default='', null=True)),
                ('p2', models.TextField(blank=True, default='', null=True)),
                ('p3', models.TextField(blank=True, default='', null=True)),
                ('p4', models.TextField(blank=True, default='', null=True)),
                ('p5', models.TextField(blank=True, default='', null=True)),
                ('p6', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='grados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_grado', models.IntegerField(blank=True, null=True)),
                ('nombre_grado', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='opiniones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(blank=True, default='', null=True)),
                ('nombre_empresa', models.TextField(blank=True, default='', null=True)),
                ('id_encuesta', models.IntegerField(blank=True, default='0', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(blank=True, default='No configurado', null=True)),
                ('nombre', models.TextField(blank=True, default='', null=True)),
                ('apellido', models.TextField(blank=True, default='', null=True)),
                ('id_grado', models.IntegerField(blank=True, default='0', null=True)),
            ],
        ),
    ]
