# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-10 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sopa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='nombre_empresa',
            field=models.TextField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='tutor',
            field=models.TextField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='ubicacion',
            field=models.TextField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='opiniones',
            name='nombre_empresa',
            field=models.TextField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='opiniones',
            name='user',
            field=models.TextField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='apellido',
            field=models.TextField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.TextField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='user',
            field=models.TextField(blank=True, default='No configurado', max_length=15, null=True),
        ),
    ]
